"""
TweetDrafter — generates tweet drafts from pipeline data using the LLM.

Reads today's pipeline run funnel stats and signal history from SQLite,
sends the data to the LLM with content templates, and saves 1-2 draft
options to ``data/tweet_drafts/{date}.json``.

Usage::

    from crypto_swing_copilot.social.tweet_drafter import TweetDrafter

    drafter = TweetDrafter()
    draft = drafter.draft()  # generates draft for today
"""

from __future__ import annotations

import json
import logging
from datetime import UTC, date, datetime
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field

from crypto_swing_copilot.agents.base import (
    call_llm,
    load_agent_config,
    parse_json_response,
)
from crypto_swing_copilot.config import DATA_DIR

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------

class TweetOption(BaseModel):
    """A single tweet draft option generated by the LLM."""
    model_config = ConfigDict(frozen=True)

    text: str = Field(..., description="Tweet text (280 char limit)")
    tweet_type: str = Field(
        ...,
        description="Category: funnel_report | market_commentary | philosophy | signal_day",
    )
    thread: list[str] = Field(
        default_factory=list,
        description="Thread continuation tweets (each <= 280 chars, 1-3 replies)",
    )


class TweetDraftResponse(BaseModel):
    """LLM response containing 1-2 tweet draft options."""
    model_config = ConfigDict(frozen=True)

    options: list[TweetOption] = Field(
        ..., min_length=1, max_length=2,
        description="1-2 tweet draft options to choose from",
    )
    reasoning: str = Field(..., description="Why these angles were chosen")


class TweetDraftFile(BaseModel):
    """Persisted draft file at data/tweet_drafts/{date}.json."""
    report_date: str
    generated_at: str
    pipeline_context: dict
    drafts: TweetDraftResponse
    image_paths: list[str] = Field(
        default_factory=list,
        description="Paths to attached images (future use)",
    )
    posted: bool = False


# ---------------------------------------------------------------------------
# System prompt
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = """\
You are a tweet ghostwriter for The Tenth Floor — an AI-powered crypto swing-trade \
analysis service built by a solo founder. The AI scans 26 pairs daily through 7 \
filtering gates and publishes max 2 signals per day. Most days it publishes zero.

You receive today's pipeline data. Draft 1-2 tweet options.

STRUCTURE — every tweet MUST follow this pattern:
1. HOOK (1-2 sentences, <= 280 chars) — creates curiosity or makes a bold claim.
   This is the main tweet. It must make someone stop scrolling.
2. THREAD (1-3 replies, each <= 280 chars) — delivers the substance the hook promised.
   Explain, teach, or reveal the data. This is where value lives.

The hook opens a loop. The thread closes it. Never hook without delivering.

VOICE:
- Founder building in public. First person ("I built", "my AI").
- Short declarative sentences. No filler, no fluff.
- Teach something in every thread. The reader should learn how the system works.
- Zero hashtags. Zero emojis. Zero "GM" or crypto-twitter slang.
- Never hype. Never promise returns. Never financial advice.
- The AI is a tool you built — talk about it like an engineer, not a marketer.
- Vary your openings. Never start two drafts the same way.

TWEET TYPES (pick the best fit for today's data):

1. FUNNEL REPORT — The pipeline stats tell a story. Use them.
   Hook: "I built a 7-gate filter for crypto signals. Gate 1 alone killed 19 out \
of 26 pairs today."
   Thread: Explain what each gate does and why most pairs die at trend regime. \
Use the real numbers from today's funnel.

2. MARKET COMMENTARY — React to Fear & Greed or macro conditions.
   Hook: "Fear & Greed hit 13 today. Here's how my trading AI responds to \
extreme fear."
   Thread: Explain the capitulation bypass, why direction matters more than \
level, what conditions would trigger a buy in extreme fear.

3. PHILOSOPHY — Explain a design decision. Teach the reader something.
   Hook: "My AI has a minimum R:R of 2.0. Here's what that means and why most \
setups fail it."
   Thread: Explain risk-reward, how the gate works, give a concrete example \
of a setup that looked good but got killed by R:R.

4. SIGNAL DAY — When there ARE approved signals. Tease, don't reveal.
   Hook: "First signal in 8 days. 26 pairs, 7 gates, and one made it through."
   Thread: Talk about what made today different — market conditions, which \
gates were the hardest to pass. Never reveal the pair or price levels.

RULES:
- Main tweet (hook) MUST be <= 280 characters. Count carefully.
- Thread tweets each <= 280 characters.
- ALWAYS include at least 1 thread reply. The hook alone is not enough.
- Never reveal specific pairs, entry prices, or stop losses.
- Use real numbers from the data provided. Don't make up stats.
- Respond with valid JSON only. No markdown, no explanation outside JSON.

OUTPUT FORMAT:
{
  "options": [
    {
      "text": "<hook tweet, <= 280 chars>",
      "tweet_type": "<funnel_report|market_commentary|philosophy|signal_day>",
      "thread": ["<thread reply 1>", "<thread reply 2 (optional)>"]
    }
  ],
  "reasoning": "<why you chose this angle for today's data>"
}
"""


# ---------------------------------------------------------------------------
# TweetDrafter
# ---------------------------------------------------------------------------

class TweetDrafter:
    """Generates tweet drafts from pipeline data using the LLM."""

    def __init__(self, db_path: Path | str | None = None) -> None:
        self._config = load_agent_config("tweet_drafter")
        self._drafts_dir = DATA_DIR / "tweet_drafts"
        self._drafts_dir.mkdir(parents=True, exist_ok=True)

        # Lazy DB import to avoid circular deps
        from crypto_swing_copilot.db.signal_logger import SignalLogger
        self._db = SignalLogger(db_path)

    def draft(self, report_date: str | None = None) -> TweetDraftFile:
        """Generate tweet drafts for a given date.

        Parameters
        ----------
        report_date:
            ISO date (YYYY-MM-DD). Defaults to today.

        Returns
        -------
        TweetDraftFile
            Saved draft with 1-2 tweet options.
        """
        if report_date is None:
            report_date = date.today().isoformat()

        context = self._query_pipeline_context(report_date)
        user_prompt = self._build_prompt(context)

        logger.info("Generating tweet drafts for %s", report_date)
        raw = call_llm(
            agent_name="tweet_drafter",
            system_prompt=_SYSTEM_PROMPT,
            user_prompt=user_prompt,
            **{k: v for k, v in self._config.items()
               if k in ("model", "temperature", "max_output_tokens",
                         "provider", "base_url", "timeout", "max_retries")},
        )

        drafts = parse_json_response(raw, TweetDraftResponse)

        # Validate char limits — truncate if LLM exceeded 280
        validated_options = []
        for opt in drafts.options:
            text = opt.text[:280] if len(opt.text) > 280 else opt.text
            thread = [t[:280] for t in opt.thread]
            validated_options.append(TweetOption(
                text=text, tweet_type=opt.tweet_type, thread=thread,
            ))
        drafts = TweetDraftResponse(
            options=validated_options, reasoning=drafts.reasoning,
        )

        draft_file = TweetDraftFile(
            report_date=report_date,
            generated_at=datetime.now(UTC).isoformat(),
            pipeline_context=context,
            drafts=drafts,
        )

        path = self._save_draft(draft_file)
        logger.info("Tweet draft saved to %s", path)
        return draft_file

    def _query_pipeline_context(self, report_date: str) -> dict:
        """Pull funnel stats and signal history from SQLite."""
        pipeline_run = self._db.get_pipeline_run(report_date)
        days_since = self._days_since_last_signal(report_date)
        track_record = self._recent_track_record()

        return {
            "report_date": report_date,
            "pipeline_run": pipeline_run,
            "days_since_last_signal": days_since,
            "track_record": track_record,
        }

    def _days_since_last_signal(self, report_date: str) -> int | None:
        """Count days between report_date and most recent published signal."""
        last_date = self._db.get_last_published_date()
        if last_date is None:
            return None
        try:
            rd = date.fromisoformat(report_date)
            ld = date.fromisoformat(last_date)
            return (rd - ld).days
        except ValueError:
            return None

    def _recent_track_record(self, lookback_days: int = 30) -> dict:
        """Aggregate TP/SL/expired/active counts for last N days."""
        signals = self._db.get_recent_signals(lookback_days)
        tp = sum(1 for s in signals if s.get("status") == "HIT_TP")
        sl = sum(1 for s in signals if s.get("status") == "HIT_SL")
        expired = sum(1 for s in signals if s.get("status") == "EXPIRED")
        active = sum(1 for s in signals if s.get("status") in ("PENDING", "OPEN"))
        return {
            "total_published": len(signals),
            "hit_tp": tp,
            "hit_sl": sl,
            "expired": expired,
            "active": active,
        }

    def _build_prompt(self, context: dict) -> str:
        """Build the user prompt from pipeline context."""
        run = context.get("pipeline_run") or {}
        tr = context.get("track_record", {})

        fg_value = run.get("fear_greed_value", "unknown")
        fg_label = _fg_label(fg_value) if isinstance(fg_value, int) else "unknown"

        lines = [
            f"DATE: {context['report_date']}",
            "",
            "FUNNEL:",
            f"- Pairs analyzed: {run.get('pairs_analyzed', 0)}",
            f"- Killed at trend gate: {run.get('killed_trend_gate', 0)}",
            f"- Killed at strategy: {run.get('killed_strategy_skip', 0)}",
            f"- Killed at volume gate: {run.get('killed_volume_gate', 0)}",
            f"- Killed at BTC RS: {run.get('killed_rs_gate', 0)}",
            f"- Killed at confidence: {run.get('killed_confidence_gate', 0)}",
            f"- Killed at R:R gate: {run.get('killed_rr_gate', 0)}",
            f"- Killed at BTC correlation: {run.get('killed_btc_corr_gate', 0)}",
            f"- Killed at sector cap: {run.get('killed_sector_cap', 0)}",
            f"- Approved: {run.get('approved', 0)}",
            f"- Published: {run.get('published', 0)}",
            "",
            f"FEAR & GREED: {fg_value} ({fg_label})",
            "",
            f"DAYS SINCE LAST SIGNAL: {context.get('days_since_last_signal', 'never')}",
            "",
            "RECENT TRACK RECORD (last 30 days):",
            f"- Signals published: {tr.get('total_published', 0)}",
            f"- Hit TP: {tr.get('hit_tp', 0)}",
            f"- Hit SL: {tr.get('hit_sl', 0)}",
            f"- Expired: {tr.get('expired', 0)}",
            f"- Still active: {tr.get('active', 0)}",
            "",
            "Draft 1-2 tweet options based on this data.",
        ]
        return "\n".join(lines)

    def _save_draft(self, draft_file: TweetDraftFile) -> Path:
        """Save draft to data/tweet_drafts/{date}.json."""
        path = self._drafts_dir / f"{draft_file.report_date}.json"
        path.write_text(
            json.dumps(draft_file.model_dump(), indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        return path

    def close(self) -> None:
        """Close the DB connection."""
        self._db.close()

    def __enter__(self) -> TweetDrafter:
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()


def _fg_label(value: int) -> str:
    """Map Fear & Greed index to a human label."""
    if value <= 25:
        return "Extreme Fear"
    if value <= 45:
        return "Fear"
    if value <= 55:
        return "Neutral"
    if value <= 75:
        return "Greed"
    return "Extreme Greed"
